---
- name: Add IP to MikroTik Address List
  hosts: all
  gather_facts: no
  vars:
    ip: 10.20.30.40
    ipcomment: "comment"
    addreslist: listname
  vars_files:
    mikrotik_vars
  tasks:
    - name: Add IP to Address List
      community.routeros.command:
        commands:
          - "/ip firewall address-list add list={{ addresslist }} address={{ ip }} comment={{ ipcomment }}"
      register: result

    - name: Debug Output
      debug:
        var: result